### ISSUE TITLE
Smooth Piece Placement

### ISSUE THREAD

**Issue by timhhsieh** [Phil1999/PicturePerfect#18]
Selecting and placing pieces is kinda clunky right now. We should improve it to be more smooth.

**Comment by Phil1999** [comment]
I think I figured out what I was noticing. Basically in **PlayState** in the function
```swift
private func showWrongPlacementAnimation(for piece: SKSpriteNode)
```

we have the line
```swift
EffectManager.shared.disableInteraction()
```
which disables user input for a bit and this is what was causing placement to be a bit clunky.
